# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:12
from __future__ import unicode_literals

import apptb.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apptb.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('invoice_details_1', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_details_2', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_details_3', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_details_4', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_details_5', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_details_6', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('document', models.FileField(editable=False, null=True, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units', models.CharField(max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Client')),
            ],
        ),
        migrations.CreateModel(
            name='RecvPayment',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('external_id_desc', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('short_desc', models.CharField(max_length=128)),
                ('long_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Project')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apptb.InvoiceLine'),
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Task'),
        ),
    ]
