# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptb', '0002_auto_20170830_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['task', 'started_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['date', 'activity'], 'verbose_name': 'Charge', 'verbose_name_plural': 'Charges'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['code'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['number'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['invoice', 'index'], 'verbose_name': 'Invoice Line', 'verbose_name_plural': 'Invoice Lines'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='recvpayment',
            options={'ordering': ['date', 'client'], 'verbose_name': 'Received Payment', 'verbose_name_plural': 'Received Payments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'date', 'short_desc'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='document',
        ),
        migrations.AddField(
            model_name='invoice',
            name='filename',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
