# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:50
from __future__ import unicode_literals

import apptb.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptb', '0003_auto_20170902_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWebKey',
            fields=[
                ('id', models.CharField(default=apptb.utils.pk8, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('key', models.CharField(default=apptb.utils.pk16, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptb.Client')),
            ],
            options={
                'ordering': ['client', 'id'],
                'verbose_name': 'Client Web Key',
                'verbose_name_plural': 'Client Web Keys',
            },
        ),
    ]
